# Generated by Django 5.1.2 on 2024-10-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdate',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
